### ISSUE TITLE
 MemcachePool::replace(): The lowest two bytes of the flags array is reserved for pecl/memcache internal use

### ISSUE THREAD

**Issue by snowballrandom** [pierskarsenbarg/codeigniter-session-memcached#3]
Noticed this error:

Severity: Warning

Message: MemcachePool::replace(): The lowest two bytes of the flags array is reserved for pecl/memcache internal use

Filename: libraries/MY_Session.php

Line Number: 322

Either need to use the memcached server by changing 
      $this->memcached = new Memcache();
to 
      $this->memcached = new Memcached();
on line 97

Or add the compression flag as a third paramer i.e. MEMCACHE_COMPRESSED on lines 
 322 and 365 in MY_Session.php

**Comment by reina3596** [comment]
Perfect Solution¡¡¡ ;)
